### ISSUE TITLE
Pool not importing on boot Ubuntu 15.04

### ISSUE THREAD

**Issue by palesius** [zfsonlinux/pkg-zfs#162] opened 2015-07-15 15:42 UTC
I have a fresh install of Ubuntu 15.04 that I've set up a zfs pool on.
However every time I reboot I have to manually import.

I don't see any any errors in dmesg: http://pastebin.com/Fq5icG8X 
it completes boot around 80.

I've verified (using apt-cache policy mountall) that I have the correct version of mountall.
I've tried deleting /etc/zfs/zpool.cache and it seems to recreate it just fine

I haven't been able to find where to look at the logs (if any) from mountall.

upstart was not initially installed. I have since installed it, and removed and reinstalled the ubuntu-zfs package after installing upstart.

Same behavior.

This could all very well be down to user error, as this is my first ubuntu build, I'm far more familiar with fedora/centos and my experience with ZFS is all on FreeBSD.

**Comment by palesius** [comment] 2015-07-15 16:49
Ok I resolved the issue by switching it to use upstart instead of sysv:
sudo apt-get install upstart-sysv

However automounting does not appear to work on Ubuntu 15.04 without this change.

**Comment by dajhorn** [comment] 2015-07-20 06:56
This is a duplicate of #145 and #161; better systemd support is pending.

**Closed as completed by dajhorn** 2015-07-20 06:56 UTC
