### ISSUE TITLE
ZoL 0.6.4 zpool status disk name regression on Ubuntu

### ISSUE THREAD

**Issue by d33psky** [zfsonlinux/pkg-zfs#152] opened 2015-04-20 13:31 UTC
Using 0.6.4-3~trusty packages on Ubuntu 14.04 the disk names with which a pool was made change into sda-like names after a reboot. This prevents identifying a disk by its type and serial number like what was possible on (at least) 0.6.2

For example I make a pool :

zpool create tank raidz2 ata-HGST_HUS724030ALA640_PN1234P8KJRZKX ata-HGST_HUS724030ALA640_PN1234P8KJJNZX ...

and before a reboot these get listed as expected :

zpool status
pool: tank
state: ONLINE
scan: none requested
config:
NAME STATE READ WRITE CKSUM
tank ONLINE 0 0 0
raidz2-0 ONLINE 0 0 0
ata-HGST_HUS724030ALA640_PN1A38P3G58S1B ONLINE 0 0 0
ata-HGST_HUS724030ALA640_PN1A38P3G2GJ2B ONLINE 0 0 0
...

However after a reboot they show up as :

zpool status
pool: tank
state: ONLINE
scan: none requested
config:
NAME STATE READ WRITE CKSUM
tank ONLINE 0 0 0
raidz2-0 ONLINE 0 0 0
sdc ONLINE 0 0 0
sdd ONLINE 0 0 0
...

I need these to show with the names the pool was created with.

Extra info from zfs-discuss ( http://list.zfsonlinux.org/pipermail/zfs-discuss/2015-April/000764.html ) : this issue does not show on CentOS 6 or EL7 but is confirmed on Ubuntu with this additional info : "Saw this happen on my ubuntu system too after upgrading to 0.6.4
Interesting detail was that it happened only to about half of the drives in the pool. Have 2 different controllers in there. After a 'zpool export' followed by a 'zpool import -d /dev/disk/by-id'
things are back to normal, even through subsequent reboots."

This issue seems related to #148

**Comment by dasjoe** [comment] 2015-05-26 19:11
It's a duplicate of #148, yes. Manually exporting and reimporting like you quoted should fix this, at least in `zdb` output.

**Comment by dajhorn** [comment] 2015-07-16 23:29
Closing as a duplicate.

**Closed as completed by dajhorn** 2015-07-16 23:29 UTC
