### ISSUE TITLE
zfs does not mount non-empty parent directory on boot

### ISSUE THREAD

**Issue by macrocreation** [zfsonlinux/pkg-zfs#43] opened 2012-08-29 10:03 UTC
We;ve noticed an issue with mountall where at boottime files placed in the root directory vanish.

The boot time troubles are a result of zfs not mounting the parent folder if there are subdirectories present - the error you get is cannot mount /tank: directory is not empty. These directories are usually the result of child fs's one has created.

e.g.

$zpool create tank ....
$ cd /tank;
$ zpool create tank/fs1
$ zpool create tank/fs2
 (the above creates 2 directories fs1 and fs2 within /tank)
$ touch /tank/testfile
(creates a file call testfile)

when you reboot and use the ubuntu-zfs package -

tanks/fs1 and tank/fs2 get mounted correctly however testfile vanishes because /tank/ does not get mounted like normal.

doing a

$ zfs umount /tank/fs1
$ rm -rf /tank/fs1
$ zfs umount /tank/fs2
$ rm -rf /tank/fs2
$ zfs mount -a

results in the file system being restored as you would expect i.e. testfile appear in the root dir and fs1 and fs2 appear as normal.

**Comment by dajhorn** [comment] 2012-08-30 16:21
This glitch usually means that `zfs mount -a` is invoked during system start, which should not happen on Ubuntu.  The `mountall` utility that is installed by `ubuntu-zfs` does not preserve Solaris behavior and will use non-empty mount points.

Double-check that:
- The `/etc/init.d/zfs` file does not exist. Leftovers from a `make install` cause problems like this.
- Similarly, `/usr/local/sbin/zfs` and `/usr/local/lib/libzfs.so` do not exit.
- The `/etc/default/zfs` file is unmodified.  The `ZFS_MOUNT` option should be disabled.

Less frequently, this behavior can be caused by:
- Entries in the `/etc/fstab` file that conflict with `mountpoint` properties.
- A daemon running on `/tank`.  (eg: famd)

If the problem persists after running `zfs umount -a && rm -r /tank`, then:
1. Manually check that `/proc/mounts` agrees with `mount` and `zfs mount`.
2. Report version numbers for Ubuntu, ZoL, and mountall.

**Comment by macrocreation** [comment] 2012-08-30 21:09
I can confirm all the above is the case. The following though were exceptions - 
there is no /etc/init.d/zfs  however there is zfs-mount and zfs-share file.  The zfs mount does contain an zfs mount -a command
- there is a /tank/smbroot folder that is used by the smbd daemon
- there is also a /tank/vicepa folder that is used by openafs 

Could these point to where the issues are coming from?

hb

**Comment by dajhorn** [comment] 2012-08-30 21:34
>  The following though were exceptions - there is no /etc/init.d/zfs however there is zfs-mount and zfs-share file.

This is proper if you are using the PPA.

> - there is a /tank/smbroot folder that is used by the smbd daemon
> - there is also a /tank/vicepa folder that is used by openafs
> 
> Could these point to where the issues are coming from?

Temporarily disabling both services, cleaning the mount point, and rebooting is an easy way to check.

Note that moving the service mounts up and out of the tank is a way to kludge the problem:

```
 # zfs set mountpoint=/smbroot tank/smbroot
 # zfs set mountpoint=/vicepaa tank/vicepaa
 # : dismount, clean the /tank, and remount
 # ln -s /smbroot /tank/smbroot
 # ln -s /vicepaa /tank/vicepaa
```

**Comment by dajhorn** [comment] 2012-09-15 04:13
I am closing this ticket because it has gone two weeks without an update.  If the problem persists, then please reopen the issue.

**Comment by macrocreation** [comment] 2012-11-26 20:36
Hi, Just providing an update on this issue as I have had some time to work on it.

Basically - if /tank is non-empty mountall does not work.

Mounting all tank/ child fs in different rootdirs and leaving tank empty fixes the problem. Don't know why.

**Comment by dajhorn** [comment] 2012-11-26 21:06
Okay, thanks for the update.  This ticket is reopened so that other people can see it.

I suspect that the problem is caused by an unhandled corner case in the system shutdown logic, but I won't be able to properly diagnose it until I can get a reproducer.

**Comment by ptman** [comment] 2013-11-26 09:28
I had the same problem. Apparently during reboot after upgrade from linux-image-3.2.0-55-generic to linux-image-3.2.0-56-generic. I unmounted everything, removed the empty directories under /tank that were apparently present on the ext4 root filesystem. After that zfs mount -a did the trick and /tank was mounted along with the child datasets.

**Comment by dajhorn** [comment] 2016-04-28 17:06
Given that the systemd stack fully superseded upstart and mountall -- thereby mooting these issues -- I will close this ticket as stale.

**Closed as completed by dajhorn** 2016-04-28 17:06 UTC
Labels: Erratum

**Comment by ptman** [comment] 2016-04-28 17:25
I hope everyone on trusty will be able to upgrade to xenial

**Comment by dajhorn** [comment] 2016-04-28 17:31
@ptman, 

> I hope everyone on trusty will be able to upgrade to xenial

Ubuntu doesn't have an officially supported upgrade path between Trusty and Xenial for ZoL features.

That said, simple in-pool configurations should migrate easily.  Systems that use `upstart` events, `/etc/fstab` customizations, or a ZFS root filesystem will need attention.

Please bench test all upgrades.
