### ISSUE TITLE
zfsutils insserv issues

### ISSUE THREAD

**Issue by whatarcane** [zfsonlinux/pkg-zfs#169] opened 2015-09-20 17:58 UTC
On a fresh install of Debian Jessie, installing ZFSonLinux as per instructions at http://zfsonlinux.org/debian.html :

Setting up zfsutils (0.6.5.1-2) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: start runlevel arguments (S) do not match zfs-zed Default-Start values (2 3 4 5)
insserv: Service zfs-mount has to be enabled to start service zfs-zed
insserv: exiting now!
update-rc.d: error: insserv rejected the script header

The issue is fixed by manually doing (in order):
insserv zfs-import
insserv zfs-mount
insserv zfs-zed
dpkg --configure  debian-zfs  zfsutils

**Comment by hostingnuggets** [comment] 2015-09-21 12:09
same here on a fresh install of Debian 8.2 (amd64)

**Comment by FransUrbo** [comment] 2015-09-21 12:11
Duplicate of zfsonlinux/zfs#2680.

**Closed as completed by FransUrbo** 2015-09-21 12:11 UTC
