### ISSUE TITLE
Debian Jessie: zfsutils fails to configure

### ISSUE THREAD

**Issue by jpapadopoulos** [zfsonlinux/pkg-zfs#168] opened 2015-09-20 14:31 UTC
This is the relevant console output:

Setting up zfsutils (0.6.5.1-2) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: start runlevel arguments (S) do not match zfs-zed Default-Start values (2 3 4 5)
insserv: Service zfs-mount has to be enabled to start service zfs-zed
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package zfsutils (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of debian-zfs:
 debian-zfs depends on zfsutils; however:
  Package zfsutils is not configured yet.

dpkg: error processing package debian-zfs (--configure):
 dependency problems - leaving unconfigured
Processing triggers for initramfs-tools (0.120) ...
update-initramfs: Generating /boot/initrd.img-3.16.0-4-amd64
Errors were encountered while processing:
 zfsutils
 debian-zfs
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to perform requested operation on package.  Trying to recover:
Setting up zfsutils (0.6.5.1-2) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: start runlevel arguments (S) do not match zfs-zed Default-Start values (2 3 4 5)
insserv: Service zfs-mount has to be enabled to start service zfs-zed
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package zfsutils (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of debian-zfs:
 debian-zfs depends on zfsutils; however:
  Package zfsutils is not configured yet.

dpkg: error processing package debian-zfs (--configure):
 dependency problems - leaving unconfigured
Processing triggers for initramfs-tools (0.120) ...
update-initramfs: Generating /boot/initrd.img-3.16.0-4-amd64
Errors were encountered while processing:
 zfsutils
 debian-zfs

if any more info is required let me know.

**Comment by FransUrbo** [comment] 2015-09-20 15:00
This might be a duplicate of zfsonlinux/zfs#2680.

**Closed as completed** 2015-09-20 15:00 UTC
